import turtle
p=turtle.Turtle()
turtle.bgcolor("black")

#Body of Phone
p.pensize(15)
p.speed(0)
p.penup()
p.goto(-150,-150)
p.pendown()
p.color("cadetblue4")
p.begin_fill()
p.fd(210)
p.lt(90)
p.fd(390)
p.lt(90)
p.fd(210)
p.lt(90)
p.fd(390)
p.end_fill()

#Screen of Mobile
p.penup()
p.goto(-150,-150)
p.pendown()
p.pensize(5)
p.color("black")
p.begin_fill()
p.lt(90)
p.fd(210)
p.lt(90)
p.fd(390)
p.lt(90)
p.fd(210)
p.lt(90)
p.fd(390)
p.end_fill()

#FrontCam
p.penup()
p.goto(-51,231)
p.pendown()
p.pensize(1)
p.pencolor("gray35")
p.circle(7)

#Innerlens of FrontCam
p.penup()
p.goto(-47,231)
p.pendown()
p.fillcolor("lightsteelblue4")
p.begin_fill() 
p.circle(3)
p.end_fill()

p.penup()
p.goto(-120,130)
p.pendown()
p.pencolor("darkgoldenrod1")
p.write("TEJA - 테자 - テジャ",font=("arial",13,"bold"))

#Volume and Power Buttons
p.penup()
p.goto(69,170)
p.pendown()
p.pensize(4)
p.pencolor("cadetblue4")
p.fd(55)
p.penup()
p.fd(20)
p.pendown()
p.fd(30)

p.hideturtle()
turtle.exitonclick()